[project]
name = "nodellm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "langchain[google-genai,openai]>=1.2.9",
    "langchain-google-genai>=4.2.0",
    "langchain-openai>=1.1.7",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.40.0",
    "asyncpg>=0.31.0",
    "greenlet>=3.3.1",
    "sqlalchemy>=2.0.46",
    "networkx>=3.6.1",
    "fastapi>=0.135.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.5",
]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
