from fastapi import APIRouter, Depends

from core import NodeService, get_node_service, get_ai_model, build_context
from llm import AiRequest, AiResponse, SummaryRequest
from llm import PromptNodeModel, SummaryNodeModel

llm_router = APIRouter(prefix="/llm", tags=["llm"])


@llm_router.post("/llm/generate")
async def get_response(
    data: AiRequest,
    service: NodeService = Depends(get_node_service),
    ai_model: PromptNodeModel = Depends(get_ai_model),
) -> AiResponse:
    """
    Handles AI response generation from a given prompt and context through a specified AI model and service.

    This function processes an input request to generate a response using the provided
    service and AI model dependencies. The function first builds the required context
    based on the target ID and then generates a response by invoking the AI model with
    the generated context and input prompt.

    Args:
        data (AiRequest): Input request object containing the prompt and target identifier.
        service (NodeService): Dependency that provides the node service instance.
        ai_model (PromptNodeModel): Dependency that provides the AI model instance.

    Returns:
        AiResponse: The response generated by the AI model based on the input prompt and context.
    """
    if not data.include_context:
        return await ai_model.generate_without_context(data.prompt)

    context = await build_context(service, data.target_id)
    return await ai_model.generate(context, data.prompt)


@llm_router.post("/llm/summarize")
async def summarize(
    data: SummaryRequest,
    service: NodeService = Depends(get_node_service),
    ai_model: SummaryNodeModel = Depends(get_ai_model),
) -> AiResponse:
    context = await build_context(service, data.target_id)
    return await ai_model.generate(context, "generate a summary")
