import uuid
from uuid import UUID

from fastapi import APIRouter, Depends

from data import NodeRead, PromptRequest
from llm import AiModel, Response
from llm.service import PromptService
from src.core.context.model import Context
from src.core.dependencies import get_ai_model, get_context

llm_router = APIRouter(prefix="/llm", tags=["LLM"])


@llm_router.post("/generate/{target_id}")
async def generate_response(
    ctx: Context = Depends(get_context),
    ai_model: AiModel = Depends(get_ai_model),
) -> Response:
    service = PromptService(ai_model)
    return await service.generate_graph_response(ctx)


@llm_router.post("/test")
async def test_response(request: PromptRequest) -> NodeRead:
    node = NodeRead(
        id=request.target_id,
        type="Nodle",
        pos_x=100,
        pos_y=100,
        data={
            "label": "test label",
            "prompt": request.prompt,
            "response": """To add Markdown support, the standard approach in React is to use the **`react-markdown`** library. It’s lightweight, secure, and works perfectly with Tailwind.

### 1. Install the dependencies
You'll need the main library and a plugin called `remark-gfm` if you want support for tables, checklists, and strikethroughs.

```bash
npm install react-markdown remark-gfm
```

### 2. Update your code
Import the component and wrap your `{data.response}`. I've also added a **`prose`** class from Tailwind's Typography plugin (or custom styles) to ensure the Markdown elements (like bold, lists, and links) actually look correct.

```tsx
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

// ... inside your return
<div className="text-sm/6 text-black bg-white/5 border border-white/10 p-3 rounded-lg mt-2 italic">
    {data.response ? (
        <ReactMarkdown 
            remarkPlugins={[remarkGfm]}
            className="prose prose-sm prose-slate max-w-none"
        >
            {data.response}
        </ReactMarkdown>
    ) : (
        'No response yet'
    )}
</div>
```

---

### 3. Fixing the "Unstyled" Markdown (The Typography Plugin)
By default, Tailwind resets all styles. This means your Markdown `### Headers` or `* bullets` will look like plain text. To fix this, you should install the **Tailwind Typography** plugin:

```bash
npm install -D @tailwindcss/typography
```

Then, add it to your CSS file (Tailwind 4 style):
```css
@import "tailwindcss";
@plugin "@tailwindcss/typography";
```

### Why use `prose`?


Without the `prose` class, a Markdown `**bold**` tag will have `font-weight: bold`, but a `### Header` will have no margin and the same font size as your body text. The `prose` utility automatically adds beautiful spacing, sizing, and colors to standard HTML elements generated by the Markdown parser.

### Pro-Tip: Handling Code Blocks
If your AI response includes code snippets (e.g., ` ```js `), `react-markdown` will render them as standard `<pre><code>` tags. If you want syntax highlighting (pretty colors for code), you might later want to look into a library called `react-syntax-highlighter`.

**Would you like me to show you how to customize the `prose` colors so the Markdown text matches your specific `#7dacb5` brand color?**""",
        },
    )
    return node
