from typing import Any

from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel


class NodeRead(BaseModel):
    """
    Represents a node in a graph or similar structure.

    A NodeRead object holds information about a specific node, including its
    unique identifier, type, position, and associated data. It is typically used
    to store and manage node-related attributes for processing and analysis.

    Attributes:
        id (str): The unique identifier of the node.
        type (str): The type or classification of the node.
        position (dict[str, float]): A dictionary representing the position of the
            node with keys for coordinates (e.g., x, y).
        data (dict[str, Any]): Additional data or metadata associated with the node.
    """

    id: str
    type: str
    position: dict[str, float]
    data: dict[str, Any]

    model_config = ConfigDict(from_attributes=True)


class EdgeRead(BaseModel):
    """
    Represents an edge in a graph with source and target nodes.

    This class models a directed edge in a graph structure, containing information
    about its identifier, source node, target node, and optional source and target
    handles. It is typically used for representing connections between nodes in
    graph-based systems or data structures.

    Attributes:
        id (str): Unique identifier of the edge.
        source (str): Identifier of the source node of the edge.
        target (str): Identifier of the target node of the edge.
        source_handle (str | None): Optional handle associated with the source node.
        target_handle (str | None): Optional handle associated with the target node.
    """

    id: str
    source: str
    target: str
    source_handle: str | None = None
    target_handle: str | None = None

    model_config = ConfigDict(
        from_attributes=True,
        populate_by_name=True,
        alias_generator=to_camel,
        extra="ignore",
    )


class CanvasRead(BaseModel):
    """
    Represents a Canvas with a set of nodes and edges.

    This class is used to model a canvas structure where nodes and edges define
    the relationships or connections between elements. It serves as a foundational
    data structure for applications that require graph-like representations.

    Attributes:
        nodes (list[NodeRead]): A list of nodes present in the canvas. Each node is
            represented by an instance of `NodeRead`.
        edges (list[EdgeRead]): A list of edges connecting the nodes in the canvas.
            Each edge is represented by an instance of `EdgeRead`.
    """

    nodes: list[NodeRead]
    edges: list[EdgeRead]


class AiResponse(BaseModel):
    """Represents an AI-generated response along with its title.

    This class is used to encapsulate a response generated by an AI system,
    along with a corresponding title that provides context or a label
    for the response.

    Attributes:
        response (str): The content of the AI-generated response.
    """

    response: str


class AiRequest(BaseModel):
    """
    Represents a request for AI processing.

    This class encapsulates data required to make a request for AI processing,
    including the prompt to process, the target identifier, and an optional
    source handle. It extends the `BaseModel` class and uses Pydantic
    functionality for model validation and configuration.

    Attributes:
        prompt (str): The text prompt intended for AI processing.
        target_id (str): The identifier specifying the target for the AI request.
    """

    prompt: str
    target_id: str
    include_context: bool = True

    model_config = ConfigDict(populate_by_name=True, from_attributes=True)


class SummaryRequest(BaseModel):
    """Represents a request for summarization."""

    target_id: str

    model_config = ConfigDict(populate_by_name=True, from_attributes=True)


class MergeRequest(BaseModel):
    """Represents a merge request and its associated details.

    This class is used to model the properties and data of a merge request in
    a version control context. It provides an abstraction for managing and
    communicating the target information related to the merge request.

    Attributes:
        target_id (str): Identifier of the target associated with the merge
            request.
    """

    target_id: str


class MergeResponse(BaseModel):
    """Represents a response containing merged data.

    This class is used to model the response data in scenarios where multiple
    data sources are combined or merged into a single cohesive structure. It
    provides a structured representation of the merged data.

    Attributes:
        data (list[dict[str, Any]]): A list of dictionaries representing the
            merged response data. Each dictionary contains key-value pairs that
            reflect the structure and content of the merged data.
    """

    data: list[dict[str, Any]]
